### ISSUE TITLE
MIME type error, cannot open any text file

### ISSUE THREAD

**Issue by wzurborg** [blackfennec-org/blackfennec#1]
I installed Black Fennec via flatpak on Pop!_OS 22.04 but cannot open any text file, irrespective of whether it contains JSON data or not. 

Black Fennec version: 0.11.0

Error:
```
$ flatpak run org.blackfennec.app
DEBUG:blackfennec.extension.extension:activating extension core
DEBUG:blackfennec.extension.extension:activating extension base
Gsk-Message: 11:27:43.588: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkX11Toplevel': Unable to create a GL context

INFO:blackfennec.facade.main_window.black_fennec_view:Chosen file: /run/user/1000/doc/5e127ab4/Exodus Borealis
INFO:blackfennec.facade.main_window.black_fennec_view:Chosen file: <__gi__.GLocalFile object at 0x7f150ddc6840 (GLocalFile at 0x7f14fc12fb80)>
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/blackfennec/facade/main_window/black_fennec_view.py", line 250, in on_response
    self._view_model.open_file(file.get_path())
  File "/app/lib/python3.10/site-packages/blackfennec/facade/main_window/black_fennec_view_model.py", line 62, in open_file
    self._notify('open_file', tab)
  File "/app/lib/python3.10/site-packages/blackfennec/util/observable.py", line 18, in _notify
    listener(sender, notification)
  File "/app/lib/python3.10/site-packages/blackfennec/facade/main_window/black_fennec_view.py", line 460, in on_open_tab
    Context(self, tab.document.content),
AttributeError: 'NoneType' object has no attribute 'content'
ERROR:blackfennec.facade.main_window.document_tab_view:Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/blackfennec/facade/main_window/document_tab_view.py", line 43, in load_document_async
    document = tab.load_document()
  File "/app/lib/python3.10/site-packages/blackfennec/facade/main_window/document_tab.py", line 66, in load_document
    self.document = self._document_factory.create(
  File "/app/lib/python3.10/site-packages/blackfennec/document_system/document_factory.py", line 38, in create
    mime_type = self._mime_type_registry.mime_types[mime_type_id]
KeyError: 'text/plain'

```

```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

```

**Comment by AndreasVerden** [comment]
hi @wzurborg,

Thanks for opening an issue!

Sadly Black Fennec only supports JSON files at the moment.
The long overdue version 0.12 has a partial fix for your error though:
Any files which are not supported by Black Fennec will be opened with your platform default viewer for that file type.

Let us know if that is a acceptable default behavior for your use case :)

Alternatively, we would be very happy to see you develop an extension for `text/plain`.
The documentation includes a [how to guide](http://blackfennec.pages.gitlab.ost.ch/blackfennec/development/extensions/index.html) and the repository has a few [extensions for other mime types](https://gitlab.ost.ch/blackfennec/extensions).

**Comment by wzurborg** [comment]
Hi @SimonKindhauser, thanks for your reply.

Sorry I was not specific enough in my original posting. I am getting the error irrespective of whether the file contains JSON data or not. Will add that info.

Will also look into the extension.

**Comment by AndreasVerden** [comment]
hmm, the error message you posted explicitly mentions that it failed to load a `text/plain` file. What is the file extension of your file? Maybe there is a misclassification based on that.

**Comment by wzurborg** [comment]
Are you saying you judge on the contents of a file from its file name extension? Then I was not aware of that. There are lots of JSON files having a *.txt extension. Sorry I don't have the program installed any more and I don't need it any more. And sorry for the noise. User error, closed.
